baseurl = "/"
title = "Aoif-R"
author = "Aoife O'Neill"
relativeurls = true
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Aoif-R"

[[menu.main]]
    name = "Home"
    url = "https://Aoif-R.com"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/AoifeONeill/"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/aoife-o-neill-8b3915102"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/stats_o?lang=en"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
